#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Client.Android.Resource", IsApplication=true)]

namespace Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_background_header = global::Client.Android.Resource.Color.hockeyapp_background_header;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_background_light = global::Client.Android.Resource.Color.hockeyapp_background_light;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_background_white = global::Client.Android.Resource.Color.hockeyapp_background_white;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_button_background = global::Client.Android.Resource.Color.hockeyapp_button_background;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_button_background_pressed = global::Client.Android.Resource.Color.hockeyapp_button_background_pressed;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_button_background_selected = global::Client.Android.Resource.Color.hockeyapp_button_background_selected;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_text_black = global::Client.Android.Resource.Color.hockeyapp_text_black;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_text_light = global::Client.Android.Resource.Color.hockeyapp_text_light;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_text_normal = global::Client.Android.Resource.Color.hockeyapp_text_normal;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Color.hockeyapp_text_white = global::Client.Android.Resource.Color.hockeyapp_text_white;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Drawable.hockeyapp_btn_background = global::Client.Android.Resource.Drawable.hockeyapp_btn_background;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_add_response = global::Client.Android.Resource.Id.button_add_response;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_attachment = global::Client.Android.Resource.Id.button_attachment;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_login = global::Client.Android.Resource.Id.button_login;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_refresh = global::Client.Android.Resource.Id.button_refresh;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_send = global::Client.Android.Resource.Id.button_send;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.button_update = global::Client.Android.Resource.Id.button_update;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.input_email = global::Client.Android.Resource.Id.input_email;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.input_message = global::Client.Android.Resource.Id.input_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.input_name = global::Client.Android.Resource.Id.input_name;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.input_password = global::Client.Android.Resource.Id.input_password;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.input_subject = global::Client.Android.Resource.Id.input_subject;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_author = global::Client.Android.Resource.Id.label_author;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_date = global::Client.Android.Resource.Id.label_date;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_last_updated = global::Client.Android.Resource.Id.label_last_updated;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_message = global::Client.Android.Resource.Id.label_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_text = global::Client.Android.Resource.Id.label_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_title = global::Client.Android.Resource.Id.label_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.label_version = global::Client.Android.Resource.Id.label_version;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.list_attachments = global::Client.Android.Resource.Id.list_attachments;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.list_feedback_messages = global::Client.Android.Resource.Id.list_feedback_messages;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.text_headline = global::Client.Android.Resource.Id.text_headline;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.view_header = global::Client.Android.Resource.Id.view_header;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.web_update_details = global::Client.Android.Resource.Id.web_update_details;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.wrapper_attachments = global::Client.Android.Resource.Id.wrapper_attachments;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.wrapper_feedback = global::Client.Android.Resource.Id.wrapper_feedback;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.wrapper_feedback_scroll = global::Client.Android.Resource.Id.wrapper_feedback_scroll;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.wrapper_messages = global::Client.Android.Resource.Id.wrapper_messages;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Id.wrapper_messages_buttons = global::Client.Android.Resource.Id.wrapper_messages_buttons;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_activity_expiry_info = global::Client.Android.Resource.Layout.hockeyapp_activity_expiry_info;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_activity_feedback = global::Client.Android.Resource.Layout.hockeyapp_activity_feedback;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_activity_login = global::Client.Android.Resource.Layout.hockeyapp_activity_login;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_activity_update = global::Client.Android.Resource.Layout.hockeyapp_activity_update;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_fragment_update = global::Client.Android.Resource.Layout.hockeyapp_fragment_update;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Layout.hockeyapp_view_feedback_message = global::Client.Android.Resource.Layout.hockeyapp_view_feedback_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.ApplicationName = global::Client.Android.Resource.String.ApplicationName;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.Hello = global::Client.Android.Resource.String.Hello;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::Client.Android.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_message = global::Client.Android.Resource.String.hockeyapp_crash_dialog_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button = global::Client.Android.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_crash_dialog_title = global::Client.Android.Resource.String.hockeyapp_crash_dialog_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_dialog_error_message = global::Client.Android.Resource.String.hockeyapp_dialog_error_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_dialog_error_title = global::Client.Android.Resource.String.hockeyapp_dialog_error_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_download_failed_dialog_message = global::Client.Android.Resource.String.hockeyapp_download_failed_dialog_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_download_failed_dialog_title = global::Client.Android.Resource.String.hockeyapp_download_failed_dialog_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_error_no_network_message = global::Client.Android.Resource.String.hockeyapp_error_no_network_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_expiry_info_text = global::Client.Android.Resource.String.hockeyapp_expiry_info_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_expiry_info_title = global::Client.Android.Resource.String.hockeyapp_expiry_info_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_attach_file = global::Client.Android.Resource.String.hockeyapp_feedback_attach_file;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_attach_picture = global::Client.Android.Resource.String.hockeyapp_feedback_attach_picture;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_attachment_button_text = global::Client.Android.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_attachment_error = global::Client.Android.Resource.String.hockeyapp_feedback_attachment_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_attachment_loading = global::Client.Android.Resource.String.hockeyapp_feedback_attachment_loading;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_email_hint = global::Client.Android.Resource.String.hockeyapp_feedback_email_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_failed_text = global::Client.Android.Resource.String.hockeyapp_feedback_failed_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_failed_title = global::Client.Android.Resource.String.hockeyapp_feedback_failed_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::Client.Android.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_generic_error = global::Client.Android.Resource.String.hockeyapp_feedback_generic_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_last_updated_text = global::Client.Android.Resource.String.hockeyapp_feedback_last_updated_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::Client.Android.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_message_hint = global::Client.Android.Resource.String.hockeyapp_feedback_message_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_name_hint = global::Client.Android.Resource.String.hockeyapp_feedback_name_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_refresh_button_text = global::Client.Android.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_response_button_text = global::Client.Android.Resource.String.hockeyapp_feedback_response_button_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_select_file = global::Client.Android.Resource.String.hockeyapp_feedback_select_file;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_select_picture = global::Client.Android.Resource.String.hockeyapp_feedback_select_picture;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_send_button_text = global::Client.Android.Resource.String.hockeyapp_feedback_send_button_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_send_generic_error = global::Client.Android.Resource.String.hockeyapp_feedback_send_generic_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_send_network_error = global::Client.Android.Resource.String.hockeyapp_feedback_send_network_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text = global::Client.Android.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_subject_hint = global::Client.Android.Resource.String.hockeyapp_feedback_subject_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_title = global::Client.Android.Resource.String.hockeyapp_feedback_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_validate_email_empty = global::Client.Android.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_validate_email_error = global::Client.Android.Resource.String.hockeyapp_feedback_validate_email_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_validate_name_error = global::Client.Android.Resource.String.hockeyapp_feedback_validate_name_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_validate_subject_error = global::Client.Android.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_feedback_validate_text_error = global::Client.Android.Resource.String.hockeyapp_feedback_validate_text_error;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_email_hint = global::Client.Android.Resource.String.hockeyapp_login_email_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_headline_text = global::Client.Android.Resource.String.hockeyapp_login_headline_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_headline_text_email_only = global::Client.Android.Resource.String.hockeyapp_login_headline_text_email_only;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_login_button_text = global::Client.Android.Resource.String.hockeyapp_login_login_button_text;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_missing_credentials_toast = global::Client.Android.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_login_password_hint = global::Client.Android.Resource.String.hockeyapp_login_password_hint;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_dialog_message = global::Client.Android.Resource.String.hockeyapp_paint_dialog_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button = global::Client.Android.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_indicator_toast = global::Client.Android.Resource.String.hockeyapp_paint_indicator_toast;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_menu_clear = global::Client.Android.Resource.String.hockeyapp_paint_menu_clear;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_menu_save = global::Client.Android.Resource.String.hockeyapp_paint_menu_save;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_paint_menu_undo = global::Client.Android.Resource.String.hockeyapp_paint_menu_undo;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_permission_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_permission_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_permission_update_message = global::Client.Android.Resource.String.hockeyapp_permission_update_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_permission_update_title = global::Client.Android.Resource.String.hockeyapp_permission_update_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_button = global::Client.Android.Resource.String.hockeyapp_update_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_dialog_message = global::Client.Android.Resource.String.hockeyapp_update_dialog_message;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_dialog_negative_button = global::Client.Android.Resource.String.hockeyapp_update_dialog_negative_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_dialog_positive_button = global::Client.Android.Resource.String.hockeyapp_update_dialog_positive_button;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_dialog_title = global::Client.Android.Resource.String.hockeyapp_update_dialog_title;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_mandatory_toast = global::Client.Android.Resource.String.hockeyapp_update_mandatory_toast;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.hockeyapp_update_version_details_label = global::Client.Android.Resource.String.hockeyapp_update_version_details_label;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.String.library_name = global::Client.Android.Resource.String.library_name;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Style.HockeyApp_ButtonStyle = global::Client.Android.Resource.Style.HockeyApp_ButtonStyle;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Style.HockeyApp_EditTextStyle = global::Client.Android.Resource.Style.HockeyApp_EditTextStyle;
			global::MvvX.Plugins.HockeyApp.Droid.Resource.Style.HockeyApp_SingleLineInputStyle = global::Client.Android.Resource.Style.HockeyApp_SingleLineInputStyle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyButton2 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
